* Layout for a small keyboard
/(work in progress)/

Minimal keyboard with 30 mechanical keyswitches (Cherry MX Clear), plus a row of capacitive buttons for use by both thumbs.

Conceptually, the =Main= layer is the default.  Holding a modifier key (=Shift=, =L0=, etc.) activates its corresponding layer.  If that layer overrides the =Main= layer keys, you get a different keycode as output.

| Held-down modifier: | none | Shift   | L0      | L1     | L2   | L3   |
|---------------------+------+---------+---------+--------+------+------|
| Layer Used:         | Main | Shfited | Numeric | Symbol | Main | Main |

Notably, some characters are repeated on more than one layer.  For example, period and comma are used in prose as well as programming, so they appear on both the =Main= and =Symbol= layers.  Other things could appear in multiple layers, but don't.  For example, the single- and double-quote characters only appear on the =Main= and =Shifted= layers, respectively.

* Main Layer

| q | w | e | r | t |   | y | u | i | o | p |
| a | s | d | f | g |   | h | j | k | l | ' |
| z | x | c | v | b |   | n | m | , | . | / |

* Shifted

| Q | W | E | R | T |   | Y | U | I | O | P |
| A | S | D | F | G |   | H | J | K | L | " |
| Z | X | C | V | B |   | N | M | ? | ! | : |

* Numeric

| 7 | 5 | 3 | 1 | 9 |   | 0 | 2 | 4 | 6 | 8 |
| 1 | 2 | 3 | 4 | 5 |   | 6 | 7 | 8 | 9 | 0 |
| ( | ) | : | , | % |   | . | + | - | * | / |

* Symbol

| @   | # | $ | % | [ |   | ] | ^ | & | * | \vert |
| TAB | - | + | = | ( |   | ) | ; | : | / | \     |
| _   | ~ | ` | ! | { |   | } | , | . | < | >     |
 
* Thumb Keys
These include all the modifiers (Shift, L*) as well as space, tab, enter, and backspace.  Two things of note here.
1. =Layer 3= and =Layer 2= are currently empty
2. The layer buttons are numbered 3,2,1,0 because it seemed more likely to use layer 0 and 1 with other modifiers.

| Column 0 | Column 1 | Column 2  |   | Column 3 | Column 4 | Column 5 |
|----------+----------+-----------+---+----------+----------+----------|
| Shift_L  | Tab      | Backspace |   | Space    | Enter    | Shift_R  |
| Ctrl_L   | Meta     | Alt       |   | AltGr    | Esc      | Ctrl_R   |
|          | Layer 3  | Layer 2   |   | Layer 1  | Layer 0  |          |

